### PR TITLE
Add aiohttp 3.x compatibility

### PR DESCRIPTION
**Pull request by romis2012**
Please confirm whether you agree with my fixes for aiohttp 3.x support

### CODE REVIEW

**Comment by amarynets** [comment]
When will this PR merge?

**Comment by ysangkok** [comment]
ping @nibrag

**Comment by romis2012** [comment]
This PR is obsolete, use [aiohttp-socks](https://github.com/romis2012/aiohttp-socks) package

**Comment by nibrag** [comment]
https://github.com/nibrag/aiosocks/pull/36

**Pull request closed without merging**
