### PR TITLE
Fixed for latest aiohttp version

### PR DESCRIPTION
**Pull request by TiberiumN**

### CODE REVIEW

**Comment by TiberiumPY** [comment]
@nibrag there's need for more fixes, can you do them please?

**Comment by nibrag** [comment]
@TiberiumPY ok

**Comment by Fahreeve** [comment]
Hi, I have same problem with you library. pls fix it @nibrag

**Comment by Noctem** [comment]
Any ETA for aiohttp 2.0 compatibility?

**Comment by Fahreeve** [comment]
I found fix for aiosocks 
https://github.com/panda73111/aiosocks

**Comment by Noctem** [comment]
@Fahreeve Yeah, I found that too. It'd be nice if that could be merged and put into a new release so that I can continue to just reference PyPI's aiosocks instead of a git fork in my requirements.

**Comment by nibrag** [comment]
@Noctem @TiberiumN @Fahreeve @joker-ace 

Soon I will return from the trip and fix it.
Wait 2 days, please.

**Comment by arthaud** [comment]
I fixed it here: https://github.com/arthaud/aiosocks
I could make a PR, but this is not retrocompatible. Do you want to support both aiohttp 1.x and 2.x?

**Comment by nibragimov-alytics** [comment]
fixed https://github.com/nibrag/aiosocks/pull/8

**Comment by nibrag** [comment]
fixed https://github.com/nibrag/aiosocks/pull/8

**Pull request closed without merging**
